CREATE DATABASE IF NOT EXISTS smartschool_erp;
USE smartschool_erp;

CREATE TABLE role (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  deletedAt DATETIME NULL
);

CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(20),
  passwordHash VARCHAR(255) NOT NULL,
  isActive TINYINT(1) DEFAULT 1,
  roleId INT NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  deletedAt DATETIME NULL,
  INDEX idx_user_role (roleId),
  CONSTRAINT fk_user_role FOREIGN KEY (roleId) REFERENCES role(id)
);

CREATE TABLE classRoom (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE,
  classTeacherId INT,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  deletedAt DATETIME NULL
);

CREATE TABLE section (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(10) NOT NULL,
  classRoomId INT NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  deletedAt DATETIME NULL,
  UNIQUE KEY uk_section_name_class (name, classRoomId),
  INDEX idx_section_classroom (classRoomId),
  CONSTRAINT fk_section_class FOREIGN KEY (classRoomId) REFERENCES classRoom(id)
);

-- Additional tables generated by Sequelize models are documented in backend/models/*.js.
-- Key model: studentProfile includes rfidTag (VARCHAR 64, UNIQUE) for RFID-based attendance.
